package com.digitalMedia.quiz;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.List;

public class QnA {
	public List<String> allAnswers;
	public String answer;
	public String question;
	public String selectedAnswer;
	public int selectedId = -1;
	List<QnA> quizList = new ArrayList<QnA>();
	
	public QnA () {
		super();
	}
	public QnA(String question, String answer, List<String> distractors) {
		this.question = question;
		this.answer = answer;
		this.allAnswers = new ArrayList<String>(distractors);

		allAnswers.add(answer);
		Collections.shuffle(allAnswers);
	}
	
	public boolean isCorrect() {
        return answer.equals(selectedAnswer);
    }
	
	public List<QnA> getQuestionByGameLevel(int subject) {
		if (0 == subject) {
			for(int i = 0; i < audioQuestions.length; i++) {
				quizList.add(new QnA(audioQuestions[i], audioAnswers[i], audioDistractorList.subList(i * 3, (i + 1) * 3)));
			}
			Collections.shuffle(quizList);	
		} else if (1 == subject) {
			for(int i = 0; i < imageQuestions.length; i++) {
				quizList.add(new QnA(imageQuestions[i], imageAnswers[i], imageDistractorList.subList(i * 3, (i + 1) * 3)));
			}
			Collections.shuffle(quizList);	
		}
		else if (2 == subject) {
			for(int i = 0; i < htmlQuestions.length; i++) {
				quizList.add(new QnA(htmlQuestions[i], htmlAnswers[i], htmlDistractorList.subList(i * 3, (i + 1) * 3)));
			}
			Collections.shuffle(quizList);	
		}
		return quizList;
	}
	
	String[] audioQuestions = {"A ________________ microphone is most sensitive to the sound coming from the front.",
			"A sound with higher _____ is perceived to have a higher pitch.", 
			"The number of sample points taken per second is called the _____.",
			"Reducing the number of channels from stereo (two) to mono (one) will _____.",
			"The sound wave can be represented graphically with the changes in air pressure or electrical signals plotted over time---a waveform. The _______________ axis represents time.",
			"Sound intensity is often measured in ________________.",
			"__________ is a wave that is generated by vibrating objects in a medium such as air.",
			"__________  _______ means combining multiple audio tracks with effects.",
			"What is the most common sampling rate for CD quality audio?",
			"What is not considered a general strategy for reducing digital audio file size?"
	};
    String[] audioAnswers = {"unidirectional", "frequency", "sampling rate","decrease the file size by half", "horizontal",
    		"decibels", "Sound", "Mixing Down", "44,100 Hz", "Increase the sampling rate"};
    String[] audioDistractors = {"unicorn", "MIDI", "amplitude", 
    		"tracks", "bit depth", "fidelity", 
    		"pressure", "frequency", "bit depth",
    		"increase the file size by half", "double the file size", "triple the file size",
    		"vortex", "vertical", "space",
    		"decimals", "dynamic beats", "digital bells",
    		"Envelope", "Polymorphism", "Nyquist",
    		"Fourier transforming", "Run-length encoding", "Quick masking",
    		"11,025 Hz", "96,000 Hz", "22,050 Hz",
    		"Reduce the bit depth", "Apply Compression", "Reduce the number of channels"
    };
    List<String> audioDistractorList = Arrays.asList(audioDistractors);
    
    String[] imageQuestions = {"What is a subtractive color model that stands for Cyan, Magenta, Yellow, and Black?",
			"What is an additive color model and stands for Red, Green, and Blue?",
			"The bit depth for four colors is always __ bits.", 
			"4,000 pixels x 2,000 pixels =  ____ Megapixels.",
			"An 8-bit color depth allows _____ colors.",
			"Approximately, what will happen to the file size if the total number of pixels of an image is doubled?",
			"What does HSB stand for?",
			"The term ________ comes from abridging the words: compressor and decompressor.",
			"The term pixel stands for picture _________.",
			"A ___________ of an image is a bar chart that shows the relative number of pixels plotted against a color value."
			};
    String[] imageAnswers = {"CMYK", "RGB", "3","8", "256", "the file size doubles","Hue, Saturation, and Brightness",
    		"codec", "element", "histogram"};
    String[] imageDistractors =  {"RGB", "TWAIN", "CMS", 
    		"CMYK", "ASCII", "DHTML", 
    		"2", "8", "4", 
    		"800", "8000", "6",
    		"8", "128", "1024", 
    		"the file size triples", "the file size will be half", "the file size will quadruple",
    		"Hypertext, Sampling, and Bytes", "Hue, Sampling, and Boolean", "Histogram, Saturation, and Bitmap",
    		"chrominance", "complementary", "compilation",
    		"extension", "expression", "envelope",
    		"histology", "hierarchy", "pixelation"
    		};
    List<String> imageDistractorList = Arrays.asList(imageDistractors);
    
    String[] htmlQuestions = {"HTML stands for:  ",
    		"URL stands for:  ",
    		"Dyanmic HTML is not a programming language but a combination of HTML, CSS, and _____________",
    		"A Web ___________ is an application that can display HTML documents in the correct format and layout according to the markup tags.",
    		"A file _______ refers to the location of a file on a computer, like an address to a house.",
    		"CSS stands for:  ",
    		"__________ is a scripting language web pages.",
    		"WYSIWYG stands for:  ",
    		"The ______ folder is the outermost folder of a website's structure.",
    		"Which one is an example of a valid HTML comment?"
    		};
    String[] htmlAnswers = {"HyperText Markup Language", "Uniform Resource Locator", "JavaScript","browser", "path","Cascading Style Sheets",
    		"JavaScript", "What You See Is What You Get", "root","<!--This is a comment-->"};
    
    String[] htmlDistractors = {"HyperText Music Layer", "HyperText Machine Language", "HyperText Mutator Laser",
    		"Uniform Relay Link", "Uniform Resolution Layer", "Uniform Raster Listener",
    		"Java", "JPEGs", "Flash",
    		"generator", "raster", "vector", 
    		"track", "trail", "tag",
    		"Cell Style Sheets", "Common Style Sheets", "Computer Style Sheets",
    		"DOCTYPE", "Dreamweaver", "Web Expression",
    		"What You Script Is What You Gamut", "What You Sample Is What You Get", "What You Select Is What You GIF",
    		"boot", "moot", "loot",
    		"010--This is a comment--010", "[This is a comment]","$$--This is a comment--$$"    
    };
    List<String> htmlDistractorList = Arrays.asList(htmlDistractors);
}
