var quiz = {
    questions: [
        {
            question: "A ________________ microphone is most sensitive to the sound coming from the front.",
            answer: "unidirectional",
            noise: ["unicorn", "MIDI", "amplitude"]
        },
        {
            question: "A sound with higher _____ is perceived to have a higher pitch.",
            answer: "frequency",
            noise: ["tracks", "bit depth", "fidelity"]
        },
        {
            question: "The number of sample points taken per second is called the _____.",
            answer: "sampling rate",
            noise: ["pressure", "frequency", "bit depth"]
        },
        {
            question: "Reducing the number of channels from stereo (two) to mono (one) will _____.",
            answer:  "decrease the file size by half",
            noise: ["increase the file size by half", "double the file size", "triple the file size"]
        },
        {
            question: "The sound wave can be represented graphically with the changes in air pressure or electrical signals plotted over time---a waveform. The _______________ axis represents time.",
            answer: "horizontal",
            noise: ["vortex", "vertical", "space"]
        },
            question: "Sound intensity is often measured in ________________.",
            answer: "decibels",
            noise: ["decimals", "dynamic beats", "digital bells"]
        },
        {
            question: "__________ is a wave that is generated by vibrating objects in a medium such as air.",
            answer: "Sound",
            noise: ["Envelope", "Polymorphism", "Nyquist"]
        },
        {
            question: "__________  _______ means combining multiple audio tracks with effects.",
            answer: "Mixing Down",
            noise: ["Fourier transforming", "Run-length encoding", "Quick masking"]

        },
            question: "What is the most common sampling rate for CD quality audio?",
            answer: "44,100 Hz",
            noise: ["11,025 Hz", "96,000 Hz", "22,050 Hz"]
        },
        {
            question: "What is not considered a general strategy for reducing digital audio file size?",
            answer: "Increase the sampling rate",
            noise: ["Reduce the bit depth", "Apply Compression", "Reduce the number of channels"]
        }
    ]
};
